# SPDX-License-Identifier: GPL-3.0-only
name: Prepare image metadata update
on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        options: [alpinevpn, noblevpn]
        required: true
permissions:
  contents: read
jobs:
  prepare:
    uses: ./.github/workflows/update-on-call.yml
    with:
      branch: ${{ inputs.branch }}
